name: feature-branches

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet core '6.0.401'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.401'
      - name: Build with dotnet
        run: dotnet build otp_service.sln
      - name: Run unit tests
        run: dotnet test otp_service.sln
