name: release

on:
  push:
    tags:
      - '*'
env:
  BAHMNI_VERSION: 0.94

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet core '3.1.100'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'
      - name: Build with dotnet
        run: dotnet build otp_service.sln
      - name: Run unit tests
        run: dotnet test otp_service.sln
      - name: Login to DockerHub
        uses: docker/login-action@v1S
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bahmniindiadistro/otp-service:${{env.BAHMNI_VERSION}}-${{github.run_number}},bahmniindiadistro/otp-service